### ISSUE TITLE
Remove oauth2client dependency

### ISSUE THREAD

**Issue by jone** [4teamwork/ftw.recipe.translations#8] opened 2015-11-11 15:01 UTC
The `oauth2client` has declares dependencies with `==`. This is evil! :rage: 
At least we should move the dependency to an extras.

**Comment by maethu** [comment] 2015-11-11 15:19
As I read into the code, this (Masstranslation feature) seems to be the main feature of this package, so moving this into an extra is kind of confusing.

The latest version of `oauth2client` has better dependencies declaration:

```
    'httplib2>=0.9.1',
    'pyasn1>=0.1.7',
    'pyasn1-modules>=0.0.5',
    'rsa>=3.1.4',
    'six>=1.6.1',
``` 

I prefer to move forward and use the most recent version and don't care about older Plone versions with a mess of old dependencies...

**Comment by jone** [comment] 2015-11-11 15:36
Ok then. We can easily only support newest versions because this is mainly a development tool.

**Comment by jone** [comment] 2015-11-11 15:37
By the way I think `bin/i18n-build` is used much more than masstranslate..

**Comment by maethu** [comment] 2015-11-11 15:56
Yep, but it was intended to do the masstranslation :smile: Package description says  ``ftw recipe translations import export google docs``

**Comment by jone** [comment] 2015-11-17 14:15
We require a newer `six` than Plone pins; we should really get rid of that :confused:

**Closed** 2015-11-24 13:34 UTC
